from pathlib import Path

translations = {
    "Movement": "Движение",
    "NoClip": "Проход сквозь стены",
    "Invert Controls": "Инвертировать управление",
    "Current Speed:": "Текущая скорость:",
    "(Default)": "(По умолчанию)",
    "Teleport": "Телепорт",
    "to Cursor": "к курсору",
    "to Player": "к игроку",
    "See Player Info": "Информация об игроках",
    "See Roles": "Показывать роли",
    "See Ghosts": "Показывать призраков",
    "No Shadows": "Убрать тени",
    "Task Arrows": "Стрелки заданий",
    "Reveal Votes": "Показывать голоса",
    "See Lobby Info": "Информация о лобби",
    "Camera": "Камера",
    "Zoom Out": "Отдаление камеры",
    "Spectate": "Наблюдать за игроком",
    "Freecam": "Свободная камера",
    "Tracers": "Линии до игроков",
    "Crewmates": "Члены экипажа",
    "Impostors": "Предатели",
    "Ghosts": "Призраки",
    "Dead Bodies": "Трупы",
    "Color-based": "Цвет игрока",
    "Distance-based": "По расстоянию",
    "Minimap": "Мини-карта",
    "Roles": "Роли",
    "Set Fake Role": "Подменить роль локально",
    "Set Fake Alive": "Считать себя живым",
    "Impostor": "Предатель",
    "Kill Reach": "Убийство с любого расстояния",
    "Shapeshifter": "Оборотень",
    "No Ss Animation": "Без анимации превращения",
    "Endless Ss Duration": "Бесконечное превращение",
    "Crewmate": "Член экипажа",
    "Show Tasks Menu": "Показать меню заданий",
    "Tracker": "Следопыт",
    "Endless Tracking": "Бесконечное отслеживание",
    "No Track Delay": "Без задержки отслеживания",
    "No Track Cooldown": "Без перезарядки отслеживания",
    "Track Reach": "Отслеживание на любом расстоянии",
    "Engineer": "Инженер",
    "Endless Vent Time": "Без ограничения времени в вентиляции",
    "No Vent Cooldown": "Без перезарядки вентиляции",
    "Scientist": "Учёный",
    "Endless Battery": "Бесконечная батарея",
    "No Vitals Cooldown": "Без перезарядки показателей",
    "Detective": "Детектив",
    "Interrogate Reach": "Допрос на любом расстоянии",
    "Ship": "Корабль",
    "Unfixable Lights": "Неисправимый свет",
    "Call Meeting": "Созвать собрание",
    "Close Meeting": "Закрыть собрание для себя",
    "Auto-Report Dead Bodies": "Автоматически сообщать о трупах",
    "Auto-Open Doors On Use": "Автоматически открывать двери",
    "Sabotage": "Саботаж",
    "Reactor": "Реактор",
    "Oxygen": "Кислород",
    "Lights": "Свет",
    "Comms": "Связь",
    "Show Doors Menu": "Открыть меню дверей",
    "Mushroom Mixup": "Грибная путаница",
    "Trigger Spores": "Активировать споры",
    "Open Sabotage Map": "Открыть карту саботажа",
    "Vents": "Вентиляция",
    "Unlock Vents": "Разрешить вентиляцию",
    "Kick All From Vents": "Выгнать всех из вентиляции",
    "Walk In Vents": "Двигаться в вентиляции",
    "Chat": "Чат",
    "Enable Chat": "Всегда разрешать чат",
    "Bypass URL Block": "Обход блокировки ссылок",
    "Lower Rate Limits": "Ослабить ограничения частоты",
    "Textbox": "Поле ввода",
    "Unlock Extra Characters": "Разрешить дополнительные символы",
    "Allow Longer Messages": "Разрешить длинные сообщения",
    "Unlock Clipboard": "Разрешить буфер обмена",
    "Animations": "Анимации",
    "Shields": "Щиты",
    "Asteroids": "Астероиды",
    "Empty Garbage": "Выброс мусора",
    "Medbay Scan": "Сканирование в медотсеке",
    "Cams In Use": "Камеры используются",
    "Client-Sided": "Только на клиенте",
    "Moonwalk": "Лунная походка",
    "Console": "Консоль",
    "Show Console": "Показать консоль",
    "Log Deaths": "Записывать смерти",
    "Log Shapeshifts": "Записывать превращения",
    "Log Vents": "Записывать вентиляцию",
    "Host-Only": "Только хост",
    "Kill While Vanished": "Убивать в невидимости",
    "Kill Anyone": "Убивать любого",
    "No Kill Cooldown": "Без перезарядки убийства",
    "Show Protect Menu": "Показать меню защиты",
    "Murder": "Убийства",
    "Kill Player": "Убить игрока",
    "Telekill Player": "Телепорт-убийство",
    "Kill All Crewmates": "Убить всех членов экипажа",
    "Kill All Impostors": "Убить всех предателей",
    "Kill Everyone": "Убить всех",
    "Game State": "Состояние игры",
    "Force Start Game": "Принудительно начать игру",
    "No Game End": "Запретить завершение игры",
    "Meetings": "Собрания",
    "Skip Meeting": "Пропустить собрание",
    "Vote Immune": "Иммунитет к голосованию",
    "Eject Player": "Выгнать игрока",
    "Passive": "Пассивные",
    "Free Cosmetics": "Бесплатная косметика",
    "Avoid Penalties": "Убирать штрафы за выход",
    "Unlock Extra Features": "Разблокировать дополнительные функции",
    "Copy Lobby Code on Disconnect": "Копировать код лобби при отключении",
    "Spoof Date to April 1st": "Подменить дату на 1 апреля",
    "Modes": "Режимы",
    "RGB Mode": "RGB-режим",
    "Stealth Mode": "Скрытый режим",
    "Panic Mode": "Аварийное отключение",
    "Config": "Настройки",
    "Open Config": "Открыть конфигурацию",
    "Reload Config": "Перезагрузить конфигурацию",
    "Save to Profile": "Сохранить профиль",
    "Load from Profile": "Загрузить профиль",
    "Doors": "Двери",
    "Close All": "Закрыть все",
    "Open All": "Открыть все",
    "Spam Close All": "Спам: закрыть все",
    "Spam Open All": "Спам: открыть все",
    "Spam Close": "Спам закрытием",
    "Spam Open": "Спам открытием",
    "Close": "Закрыть",
    "Open": "Открыть",
    "Tasks": "Задания",
    "✔ Complete": "✔ Выполнено",
    "Complete My Tasks": "Выполнить мои задания",
    "Complete": "Выполнить",
    "Protect Players": "Защита игроков",
    "Unprotected": "Без защиты",
    "Protected": "Под защитой",
    "Protect Everyone": "Защитить всех",
    "Keep Everyone Protected": "Постоянно защищать всех",
    "Keep protected": "Поддерживать защиту",
    "Protect": "Защитить",
    "Clear Log": "Очистить журнал",
    "Copy Log to Clipboard": "Копировать журнал",
    "Assign Roles": "Назначение ролей",
    "Reset": "Сбросить",
    "Assign": "Назначить",
    "Roles will be assigned on next game start": "Роли будут назначены при следующем запуске игры",
    "This version of MalumMenu and this version of Among Us are incompatible": "Эта версия MalumMenu несовместима с установленной версией Among Us",
    "Install the right version to avoid problems": "Установите подходящую версию, чтобы избежать проблем",
}

changed = 0
for path in Path("src").rglob("*.cs"):
    text = path.read_text(encoding="utf-8-sig")
    original = text
    for english, russian in sorted(translations.items(), key=lambda item: len(item[0]), reverse=True):
        text = text.replace(english, russian)
    if text != original:
        path.write_text(text, encoding="utf-8")
        changed += 1

if changed == 0:
    raise SystemExit("RU patch did not change any C# source files")

print(f"Russian UI patch applied to {changed} C# files")
